### ISSUE TITLE
panic: runtime error on cluster name change

### ISSUE THREAD

**Issue by yatanasov** [idealo/terraform-aws-opensearch#12] opened 2022-05-03 13:48 UTC
Hello,

We are getting the following error when trying to only rename the OpenSearch cluster:

Would it be possible for you to try and reproduce the error ? 

Thank you !

```
You may now begin working with Terraform Cloud. Try running "terraform plan" to
see any changes that are required for your infrastructure.
If you ever set or change modules or Terraform Settings, run "terraform init"
again to reinitialize your working directory.
module.opensearch.aws_iam_service_linked_role.es[0]: Refreshing state... [id=arn:aws:iam::*:role/aws-service-role/es.amazonaws.com/AWSServiceRoleForAmazonElasticsearchService]
module.opensearch.aws_elasticsearch_domain.opensearch: Refreshing state... [id=arn:aws:es:eu-west-1:*:domain/opensearch-development]
module.opensearch.aws_elasticsearch_domain_saml_options.opensearch: Refreshing state... [id=opensearch-development]

module.opensearch.elasticsearch_opendistro_roles_mapping.master_user_arn["all_access"]: Refreshing state... [id=all_access]
╷
│ Error: Plugin did not respond
│ 
│   with module.opensearch.elasticsearch_opendistro_roles_mapping.master_user_arn["all_access"],
│   on modules/opensearch/role_mapping.tf line 16, in resource "elasticsearch_opendistro_roles_mapping" "master_user_arn":
│   16: resource "elasticsearch_opendistro_roles_mapping" "master_user_arn" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Stack trace from the terraform-provider-elasticsearch_v1.6.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11504c0]
goroutine 12 [running]:
github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchGetOpenDistroRolesMapping(0xc0001bc4c2, 0xa, 0x11f0f80, 0xc0005a[98](https://github.com/LEGO/mct-ccd-aws-opensearch/runs/6274122670?check_suite_focus=true#step:6:98)c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_opendistro_roles_mapping.go:166 +0x380
github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchOpenDistroRolesMappingRead(0xc0001ee1c0, 0x11f0f80, 0xc0005a98c0, 0xc0001ee1c0, 0x0)
	github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_opendistro_roles_mapping.go:73 +0xbf
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000f5a70, 0xc00016fc70, 0x11f0f80, 0xc0005a98c0, 0xc00018b308, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:460 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000f028, 0x16946f0, 0xc0001c3080, 0xc000171320, 0xc00000f028, 0xc0001c3080, 0xc00067dba0)
	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x13f4fe0, 0xc00000f028, 0x16946f0, 0xc0001c3080, 0xc0001712c0, 0x0, 0x16946f0, 0xc0001c3080, 0xc000602000, 0xe4)
	github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e7dc0, 0x16a0678, 0xc000315380, 0xc000648800, 0xc0004777a0, 0x1eaa5d0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.33.2/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000e7dc0, 0x16a0678, 0xc000315380, 0xc000648800, 0x0)
	google.golang.org/grpc@v1.33.2/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ae230, 0xc0000e7dc0, 0x16a0678, 0xc000315380, 0xc000648800)
	google.golang.org/grpc@v1.33.2/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.33.2/server.go:869 +0x1fd
Error: The terraform-provider-elasticsearch_v1.6.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Error: Process completed with exit code 1.
```

**Comment by steveteuber** [comment] 2022-05-09 09:12
Hi @yatanasov,

Thank you for opening this issue. I can reproduce this error.
The problem is that provider configuration must be known and valid at plan time, see https://github.com/hashicorp/terraform/issues/2430.

What you can do, delete all `elasticsearch_*` resources from the state because renaming of an `aws_elasticsearch_domain` resource will trigger anyway a replacement:

```bash
terraform state rm $(terraform state list | grep ^module.opensearch.elasticsearch_)
terraform apply
```

**Comment by steveteuber** [comment] 2023-01-06 13:52
Hey @yatanasov,

Happy New Year! Can we close this issue?

**Closed** 2023-01-18 14:44 UTC
